[2024-07-20T20:01:52.633+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-20T20:01:52.655+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_ods.create_dump manual__2024-07-20T19:54:04.827161+00:00 [queued]>
[2024-07-20T20:01:52.659+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_ods.create_dump manual__2024-07-20T19:54:04.827161+00:00 [queued]>
[2024-07-20T20:01:52.659+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-20T20:01:52.667+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): create_dump> on 2024-07-20 19:54:04.827161+00:00
[2024-07-20T20:01:52.685+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2087) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-20T20:01:52.687+0000] {standard_task_runner.py:63} INFO - Started process 2089 to run task
[2024-07-20T20:01:52.686+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'refresh_ods', 'create_dump', 'manual__2024-07-20T19:54:04.827161+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/refresh_ods.py', '--cfg-path', '/tmp/tmpuly1gs1i']
[2024-07-20T20:01:52.689+0000] {standard_task_runner.py:91} INFO - Job 198: Subtask create_dump
[2024-07-20T20:01:52.771+0000] {task_command.py:426} INFO - Running <TaskInstance: refresh_ods.create_dump manual__2024-07-20T19:54:04.827161+00:00 [running]> on host 89202c950a25
[2024-07-20T20:01:52.831+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='refresh_ods' AIRFLOW_CTX_TASK_ID='create_dump' AIRFLOW_CTX_EXECUTION_DATE='2024-07-20T19:54:04.827161+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-20T19:54:04.827161+00:00'
[2024-07-20T20:01:52.835+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-20T20:01:52.843+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-20T20:01:52.844+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PGPASSWORD=*** pg_dump -h 10.82.0.4 -U etl_user_3 --data-only -n source_data -f scripts/sql-scripts/ods_dump.sql source']
[2024-07-20T20:01:52.882+0000] {subprocess.py:86} INFO - Output:
[2024-07-20T20:01:52.918+0000] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 1: unexpected EOF while looking for matching ``'
[2024-07-20T20:01:52.918+0000] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 2: syntax error: unexpected end of file
[2024-07-20T20:01:52.919+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-20T20:01:52.923+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-20T20:01:52.936+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-20T20:01:52.945+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=refresh_ods, task_id=create_dump, run_id=manual__2024-07-20T19:54:04.827161+00:00, execution_date=20240720T195404, start_date=20240720T200152, end_date=20240720T200152
[2024-07-20T20:01:52.952+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 198 for task create_dump (Bash command failed. The command returned a non-zero exit code 1.; 2089)
[2024-07-20T20:01:52.960+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-20T20:01:52.968+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-20T20:01:52.969+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
