[2024-07-20T20:04:53.332+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-20T20:04:53.345+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_ods.create_dump manual__2024-07-20T20:04:50.673399+00:00 [queued]>
[2024-07-20T20:04:53.350+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_ods.create_dump manual__2024-07-20T20:04:50.673399+00:00 [queued]>
[2024-07-20T20:04:53.350+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-20T20:04:53.357+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): create_dump> on 2024-07-20 20:04:50.673399+00:00
[2024-07-20T20:04:53.362+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-20T20:04:53.363+0000] {standard_task_runner.py:63} INFO - Started process 2132 to run task
[2024-07-20T20:04:53.363+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'refresh_ods', 'create_dump', 'manual__2024-07-20T20:04:50.673399+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/refresh_ods.py', '--cfg-path', '/tmp/tmpcymkckmf']
[2024-07-20T20:04:53.364+0000] {standard_task_runner.py:91} INFO - Job 200: Subtask create_dump
[2024-07-20T20:04:53.405+0000] {task_command.py:426} INFO - Running <TaskInstance: refresh_ods.create_dump manual__2024-07-20T20:04:50.673399+00:00 [running]> on host 89202c950a25
[2024-07-20T20:04:53.444+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='refresh_ods' AIRFLOW_CTX_TASK_ID='create_dump' AIRFLOW_CTX_EXECUTION_DATE='2024-07-20T20:04:50.673399+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-20T20:04:50.673399+00:00'
[2024-07-20T20:04:53.445+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-20T20:04:53.449+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-20T20:04:53.450+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PGPASSWORD=*** pg_dump -h 10.82.0.4 -U etl_user_3 --data-only -n source_data -f scripts/sql-scripts/ods_dump.sql source']
[2024-07-20T20:04:53.462+0000] {subprocess.py:86} INFO - Output:
[2024-07-20T20:04:53.474+0000] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 1: unexpected EOF while looking for matching ``'
[2024-07-20T20:04:53.474+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-07-20T20:04:53.475+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-20T20:04:53.480+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-07-20T20:04:53.485+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_ods, task_id=create_dump, run_id=manual__2024-07-20T20:04:50.673399+00:00, execution_date=20240720T200450, start_date=20240720T200453, end_date=20240720T200453
[2024-07-20T20:04:53.491+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 200 for task create_dump (Bash command failed. The command returned a non-zero exit code 2.; 2132)
[2024-07-20T20:04:53.506+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-20T20:04:53.516+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-20T20:04:53.517+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
