[2024-07-20T16:55:46.685+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-20T16:55:46.732+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_copy_schema_optimized_with_cache.copy_all_tables manual__2024-07-20T16:50:36.785270+00:00 [queued]>
[2024-07-20T16:55:46.742+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_copy_schema_optimized_with_cache.copy_all_tables manual__2024-07-20T16:50:36.785270+00:00 [queued]>
[2024-07-20T16:55:46.742+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-20T16:55:46.751+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): copy_all_tables> on 2024-07-20 16:50:36.785270+00:00
[2024-07-20T16:55:46.762+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=306) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-20T16:55:46.764+0000] {standard_task_runner.py:63} INFO - Started process 308 to run task
[2024-07-20T16:55:46.764+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_copy_schema_optimized_with_cache', 'copy_all_tables', 'manual__2024-07-20T16:50:36.785270+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/update_ods.py', '--cfg-path', '/tmp/tmp584gqb33']
[2024-07-20T16:55:46.766+0000] {standard_task_runner.py:91} INFO - Job 174: Subtask copy_all_tables
[2024-07-20T16:55:46.801+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_copy_schema_optimized_with_cache.copy_all_tables manual__2024-07-20T16:50:36.785270+00:00 [running]> on host 89202c950a25
[2024-07-20T16:55:46.835+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_copy_schema_optimized_with_cache' AIRFLOW_CTX_TASK_ID='copy_all_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-07-20T16:50:36.785270+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-20T16:50:36.785270+00:00'
[2024-07-20T16:55:46.837+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-20T16:55:46.840+0000] {base.py:84} INFO - Using connection ID 'source_db' for task execution.
[2024-07-20T16:55:46.980+0000] {base.py:84} INFO - Using connection ID 'target_db' for task execution.
[2024-07-20T17:14:18.047+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-07-20T17:14:18.081+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-20T17:14:18.085+0000] {process_utils.py:132} INFO - Sending 15 to group 308. PIDs of all processes in the group: [308]
[2024-07-20T17:14:18.086+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 308
[2024-07-20T17:14:21.726+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-20T17:14:21.741+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-20T17:14:21.852+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=308, status='terminated', exitcode=0, started='16:55:46') (308) terminated with exit code 0
