[2024-07-12T14:26:41.808+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T14:26:41.820+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_ods_layer.dump_source manual__2024-07-12T14:26:36.860241+00:00 [queued]>
[2024-07-12T14:26:41.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_ods_layer.dump_source manual__2024-07-12T14:26:36.860241+00:00 [queued]>
[2024-07-12T14:26:41.823+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-12T14:26:41.828+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dump_source> on 2024-07-12 14:26:36.860241+00:00
[2024-07-12T14:26:41.833+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7218) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T14:26:41.834+0000] {standard_task_runner.py:63} INFO - Started process 7220 to run task
[2024-07-12T14:26:41.834+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'init_ods_layer', 'dump_source', 'manual__2024-07-12T14:26:36.860241+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/init_ods.py', '--cfg-path', '/tmp/tmpn16c_k70']
[2024-07-12T14:26:41.835+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask dump_source
[2024-07-12T14:26:41.870+0000] {task_command.py:426} INFO - Running <TaskInstance: init_ods_layer.dump_source manual__2024-07-12T14:26:36.860241+00:00 [running]> on host 8047aa21fe02
[2024-07-12T14:26:41.921+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_ods_layer' AIRFLOW_CTX_TASK_ID='dump_source' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T14:26:36.860241+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T14:26:36.860241+00:00'
[2024-07-12T14:26:41.924+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T14:26:41.925+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-12T14:26:41.926+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n \nexport PGPASSWORD="(-\\`2loJV" &&\npg_dump -U etl_user_3 -h 10.82.0.4 -n source_data -f scripts/sql-scripts/ods_migration.sql source\n    ']
[2024-07-12T14:26:41.933+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T14:26:44.186+0000] {subprocess.py:93} INFO - pg_dump: error: could not open output file "scripts/sql-scripts/ods_migration.sql": No such file or directory
[2024-07-12T14:26:44.189+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-12T14:26:44.191+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T14:26:44.218+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-12T14:26:44.225+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=init_ods_layer, task_id=dump_source, run_id=manual__2024-07-12T14:26:36.860241+00:00, execution_date=20240712T142636, start_date=20240712T142641, end_date=20240712T142644
[2024-07-12T14:26:44.234+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 64 for task dump_source (Bash command failed. The command returned a non-zero exit code 1.; 7220)
[2024-07-12T14:26:44.267+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T14:26:44.291+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T14:26:44.296+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
