[2024-07-12T22:40:11.186+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T22:40:11.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_ods_layer.restore_ods manual__2024-07-12T22:39:57.735535+00:00 [queued]>
[2024-07-12T22:40:11.199+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_ods_layer.restore_ods manual__2024-07-12T22:39:57.735535+00:00 [queued]>
[2024-07-12T22:40:11.199+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-12T22:40:11.204+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): restore_ods> on 2024-07-12 22:39:57.735535+00:00
[2024-07-12T22:40:11.216+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1172) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T22:40:11.217+0000] {standard_task_runner.py:63} INFO - Started process 1174 to run task
[2024-07-12T22:40:11.217+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'init_ods_layer', 'restore_ods', 'manual__2024-07-12T22:39:57.735535+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/init_ods.py', '--cfg-path', '/tmp/tmpw2fgzvgr']
[2024-07-12T22:40:11.218+0000] {standard_task_runner.py:91} INFO - Job 103: Subtask restore_ods
[2024-07-12T22:40:11.239+0000] {task_command.py:426} INFO - Running <TaskInstance: init_ods_layer.restore_ods manual__2024-07-12T22:39:57.735535+00:00 [running]> on host 861c3600257c
[2024-07-12T22:40:11.268+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_ods_layer' AIRFLOW_CTX_TASK_ID='restore_ods' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T22:39:57.735535+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T22:39:57.735535+00:00'
[2024-07-12T22:40:11.269+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T22:40:11.460+0000] {logging_mixin.py:188} INFO - Ошибка при импорте схемы и данных: Command '['psql', '-U', 'etl_user_3', '-h', '10.82.0.4', '-d', 'etl_db_3', '-f', 'scripts/sql-scripts/ods_migration.sql']' returned non-zero exit status 1.
[2024-07-12T22:40:11.461+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-12T22:40:11.461+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T22:40:11.472+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=init_ods_layer, task_id=restore_ods, run_id=manual__2024-07-12T22:39:57.735535+00:00, execution_date=20240712T223957, start_date=20240712T224011, end_date=20240712T224011
[2024-07-12T22:40:11.489+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-12T22:40:11.501+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T22:40:11.502+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
