[2024-07-20T20:13:17.881+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-20T20:13:17.897+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_ods.create_dump manual__2024-07-20T20:13:11.085006+00:00 [queued]>
[2024-07-20T20:13:17.900+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_ods.create_dump manual__2024-07-20T20:13:11.085006+00:00 [queued]>
[2024-07-20T20:13:17.900+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-20T20:13:17.908+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_dump> on 2024-07-20 20:13:11.085006+00:00
[2024-07-20T20:13:17.924+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2262) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-20T20:13:17.933+0000] {standard_task_runner.py:63} INFO - Started process 2264 to run task
[2024-07-20T20:13:17.930+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'refresh_ods', 'create_dump', 'manual__2024-07-20T20:13:11.085006+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/refresh_ods.py', '--cfg-path', '/tmp/tmpdabmgvtg']
[2024-07-20T20:13:17.954+0000] {standard_task_runner.py:91} INFO - Job 207: Subtask create_dump
[2024-07-20T20:13:18.051+0000] {task_command.py:426} INFO - Running <TaskInstance: refresh_ods.create_dump manual__2024-07-20T20:13:11.085006+00:00 [running]> on host 89202c950a25
[2024-07-20T20:13:18.173+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='refresh_ods' AIRFLOW_CTX_TASK_ID='create_dump' AIRFLOW_CTX_EXECUTION_DATE='2024-07-20T20:13:11.085006+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-20T20:13:11.085006+00:00'
[2024-07-20T20:13:18.179+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-20T20:13:18.183+0000] {sql.py:276} INFO - Executing: 
        CALL pg_dump('PGPASSWORD=*** -h 10.82.0.4 -U etl_user_3 --data-only -n source_data -f scripts/sql-scripts/ods_dump.sql source');
    
[2024-07-20T20:13:18.212+0000] {base.py:84} INFO - Using connection ID 'source_db' for task execution.
[2024-07-20T20:13:18.226+0000] {base.py:84} INFO - Using connection ID 'source_db' for task execution.
[2024-07-20T20:13:18.343+0000] {sql.py:487} INFO - Running statement: 
        CALL pg_dump('PGPASSWORD=*** -h 10.82.0.4 -U etl_user_3 --data-only -n source_data -f scripts/sql-scripts/ods_dump.sql source');
    , parameters: None
[2024-07-20T20:13:18.400+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-20T20:13:18.403+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFunction: ОШИБКА:  процедура pg_dump(unknown) не существует
LINE 2:         CALL pg_dump('PGPASSWORD=*** -h 10.82.0.4 -U ...
                     ^
HINT:  Процедура с данными именем и типами аргументов не найдена. Возможно, вам следует добавить явные приведения типов.

[2024-07-20T20:13:18.453+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_ods, task_id=create_dump, run_id=manual__2024-07-20T20:13:11.085006+00:00, execution_date=20240720T201311, start_date=20240720T201317, end_date=20240720T201318
[2024-07-20T20:13:18.477+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 207 for task create_dump (ОШИБКА:  процедура pg_dump(unknown) не существует
LINE 2:         CALL pg_dump('PGPASSWORD=*** -h 10.82.0.4 -U ...
                     ^
HINT:  Процедура с данными именем и типами аргументов не найдена. Возможно, вам следует добавить явные приведения типов.
; 2264)
[2024-07-20T20:13:18.501+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-20T20:13:18.511+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-07-20T20:13:18.519+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-20T20:13:18.520+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
