[2024-07-20T20:23:16.330+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-20T20:23:16.359+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_ods.create_dump manual__2024-07-20T20:18:06.178746+00:00 [queued]>
[2024-07-20T20:23:16.366+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_ods.create_dump manual__2024-07-20T20:18:06.178746+00:00 [queued]>
[2024-07-20T20:23:16.366+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-20T20:23:16.375+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): create_dump> on 2024-07-20 20:18:06.178746+00:00
[2024-07-20T20:23:16.382+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2420) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-20T20:23:16.383+0000] {standard_task_runner.py:63} INFO - Started process 2422 to run task
[2024-07-20T20:23:16.383+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'refresh_ods', 'create_dump', 'manual__2024-07-20T20:18:06.178746+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/refresh_ods.py', '--cfg-path', '/tmp/tmp79wlp616']
[2024-07-20T20:23:16.385+0000] {standard_task_runner.py:91} INFO - Job 214: Subtask create_dump
[2024-07-20T20:23:16.421+0000] {task_command.py:426} INFO - Running <TaskInstance: refresh_ods.create_dump manual__2024-07-20T20:18:06.178746+00:00 [running]> on host 89202c950a25
[2024-07-20T20:23:16.455+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='refresh_ods' AIRFLOW_CTX_TASK_ID='create_dump' AIRFLOW_CTX_EXECUTION_DATE='2024-07-20T20:18:06.178746+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-20T20:18:06.178746+00:00'
[2024-07-20T20:23:16.457+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-20T20:23:16.459+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-20T20:23:16.460+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PGPASSWORD=*** pg_dump -h 10.82.0.4 -U etl_user_3 --data-only -n source_data -f scripts/sql-scripts/ods_dump.sql source']
[2024-07-20T20:23:16.466+0000] {subprocess.py:86} INFO - Output:
[2024-07-20T20:23:16.472+0000] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 1: unexpected EOF while looking for matching ``'
[2024-07-20T20:23:16.472+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-07-20T20:23:16.473+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-20T20:23:16.476+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-07-20T20:23:16.481+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=refresh_ods, task_id=create_dump, run_id=manual__2024-07-20T20:18:06.178746+00:00, execution_date=20240720T201806, start_date=20240720T202316, end_date=20240720T202316
[2024-07-20T20:23:16.492+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 214 for task create_dump (Bash command failed. The command returned a non-zero exit code 2.; 2422)
[2024-07-20T20:23:16.523+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-20T20:23:16.533+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-20T20:23:16.534+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
