[2024-07-12T14:24:57.106+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T14:24:57.116+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_ods_layer.dump_source manual__2024-07-12T14:24:54.461440+00:00 [queued]>
[2024-07-12T14:24:57.119+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_ods_layer.dump_source manual__2024-07-12T14:24:54.461440+00:00 [queued]>
[2024-07-12T14:24:57.119+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-12T14:24:57.124+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dump_source> on 2024-07-12 14:24:54.461440+00:00
[2024-07-12T14:24:57.130+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7182) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T14:24:57.131+0000] {standard_task_runner.py:63} INFO - Started process 7184 to run task
[2024-07-12T14:24:57.131+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'init_ods_layer', 'dump_source', 'manual__2024-07-12T14:24:54.461440+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/init_ods.py', '--cfg-path', '/tmp/tmpomqmfepj']
[2024-07-12T14:24:57.132+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask dump_source
[2024-07-12T14:24:57.153+0000] {task_command.py:426} INFO - Running <TaskInstance: init_ods_layer.dump_source manual__2024-07-12T14:24:54.461440+00:00 [running]> on host 8047aa21fe02
[2024-07-12T14:24:57.182+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_ods_layer' AIRFLOW_CTX_TASK_ID='dump_source' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T14:24:54.461440+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T14:24:54.461440+00:00'
[2024-07-12T14:24:57.185+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T14:24:57.186+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-12T14:24:57.187+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n export PGPASSWORD="(-\\2loJV" &&\npg_dump -U etl_user_3 -h 10.82.0.4 -n source_data -f scripts/sql-scripts/ods_migration.sql source\n    ']
[2024-07-12T14:24:57.196+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T14:24:57.385+0000] {subprocess.py:93} INFO - pg_dump: error: connection to server at "10.82.0.4", port 5432 failed: ВАЖНО:  пользователь "etl_user_3" не прошёл проверку подлинности (по паролю)
[2024-07-12T14:24:57.387+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-12T14:24:57.388+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T14:24:57.398+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-12T14:24:57.402+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=init_ods_layer, task_id=dump_source, run_id=manual__2024-07-12T14:24:54.461440+00:00, execution_date=20240712T142454, start_date=20240712T142457, end_date=20240712T142457
[2024-07-12T14:24:57.415+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 62 for task dump_source (Bash command failed. The command returned a non-zero exit code 1.; 7184)
[2024-07-12T14:24:57.450+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T14:24:57.464+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T14:24:57.466+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
