[2024-07-20T20:46:37.561+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-20T20:46:37.578+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_ods.restore_dump manual__2024-07-20T20:46:23.399930+00:00 [queued]>
[2024-07-20T20:46:37.581+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_ods.restore_dump manual__2024-07-20T20:46:23.399930+00:00 [queued]>
[2024-07-20T20:46:37.581+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-20T20:46:37.591+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): restore_dump> on 2024-07-20 20:46:23.399930+00:00
[2024-07-20T20:46:37.601+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2804) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-20T20:46:37.602+0000] {standard_task_runner.py:63} INFO - Started process 2806 to run task
[2024-07-20T20:46:37.602+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'refresh_ods', 'restore_dump', 'manual__2024-07-20T20:46:23.399930+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/refresh_ods.py', '--cfg-path', '/tmp/tmptah8fm43']
[2024-07-20T20:46:37.604+0000] {standard_task_runner.py:91} INFO - Job 239: Subtask restore_dump
[2024-07-20T20:46:37.641+0000] {task_command.py:426} INFO - Running <TaskInstance: refresh_ods.restore_dump manual__2024-07-20T20:46:23.399930+00:00 [running]> on host 89202c950a25
[2024-07-20T20:46:37.688+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='refresh_ods' AIRFLOW_CTX_TASK_ID='restore_dump' AIRFLOW_CTX_EXECUTION_DATE='2024-07-20T20:46:23.399930+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-20T20:46:23.399930+00:00'
[2024-07-20T20:46:37.690+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-20T20:46:37.692+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-20T20:46:37.693+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "PGPASSWORD='***' pg_restore -h 10.82.0.4 -U etl_user_3 -d etl_db_3 -v -n ods_data /opt/***/dags/scripts/sql-scripts/ods_refresh.dump"]
[2024-07-20T20:46:37.700+0000] {subprocess.py:86} INFO - Output:
[2024-07-20T20:46:37.793+0000] {subprocess.py:93} INFO - pg_restore: connecting to database for restore
[2024-07-20T20:46:37.983+0000] {subprocess.py:93} INFO - pg_restore: implied data-only restore
[2024-07-20T20:46:38.507+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-20T20:46:38.513+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-20T20:46:38.565+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=refresh_ods, task_id=restore_dump, run_id=manual__2024-07-20T20:46:23.399930+00:00, execution_date=20240720T204623, start_date=20240720T204637, end_date=20240720T204638
[2024-07-20T20:46:38.628+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-20T20:46:38.652+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-20T20:46:38.653+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
