[2024-07-17T10:47:41.187+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T10:47:41.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_ods_layer.restore_ods manual__2024-07-17T10:47:31.555657+00:00 [queued]>
[2024-07-17T10:47:41.199+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_ods_layer.restore_ods manual__2024-07-17T10:47:31.555657+00:00 [queued]>
[2024-07-17T10:47:41.199+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-17T10:47:41.203+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): restore_ods> on 2024-07-17 10:47:31.555657+00:00
[2024-07-17T10:47:41.206+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=613) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-17T10:47:41.207+0000] {standard_task_runner.py:63} INFO - Started process 615 to run task
[2024-07-17T10:47:41.207+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'refresh_ods_layer', 'restore_ods', 'manual__2024-07-17T10:47:31.555657+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/refresh_ods.py', '--cfg-path', '/tmp/tmpdzbuchnr']
[2024-07-17T10:47:41.208+0000] {standard_task_runner.py:91} INFO - Job 135: Subtask restore_ods
[2024-07-17T10:47:41.226+0000] {task_command.py:426} INFO - Running <TaskInstance: refresh_ods_layer.restore_ods manual__2024-07-17T10:47:31.555657+00:00 [running]> on host 70110a06f087
[2024-07-17T10:47:41.256+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='refresh_ods_layer' AIRFLOW_CTX_TASK_ID='restore_ods' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T10:47:31.555657+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T10:47:31.555657+00:00'
[2024-07-17T10:47:41.257+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T10:47:41.499+0000] {logging_mixin.py:188} INFO - Ошибка при импорте данных: Command '['psql', '-U', 'etl_user_3', '-h', '10.82.0.4', '-d', 'etl_db_3', '-c', 'TRUNCATE ods_data CASCADE;']' returned non-zero exit status 1.
[2024-07-17T10:47:41.500+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-17T10:47:41.500+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T10:47:41.506+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=refresh_ods_layer, task_id=restore_ods, run_id=manual__2024-07-17T10:47:31.555657+00:00, execution_date=20240717T104731, start_date=20240717T104741, end_date=20240717T104741
[2024-07-17T10:47:41.521+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-17T10:47:41.534+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-17T10:47:41.534+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
