[2024-07-12T14:50:14.041+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T14:50:14.055+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_ods_layer.dump_source manual__2024-07-12T14:50:09.103548+00:00 [queued]>
[2024-07-12T14:50:14.058+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_ods_layer.dump_source manual__2024-07-12T14:50:09.103548+00:00 [queued]>
[2024-07-12T14:50:14.058+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-12T14:50:14.067+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dump_source> on 2024-07-12 14:50:09.103548+00:00
[2024-07-12T14:50:14.077+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7561) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T14:50:14.080+0000] {standard_task_runner.py:63} INFO - Started process 7563 to run task
[2024-07-12T14:50:14.080+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'init_ods_layer', 'dump_source', 'manual__2024-07-12T14:50:09.103548+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/init_ods.py', '--cfg-path', '/tmp/tmpuvn12w56']
[2024-07-12T14:50:14.082+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask dump_source
[2024-07-12T14:50:14.114+0000] {task_command.py:426} INFO - Running <TaskInstance: init_ods_layer.dump_source manual__2024-07-12T14:50:09.103548+00:00 [running]> on host 8047aa21fe02
[2024-07-12T14:50:14.146+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_ods_layer' AIRFLOW_CTX_TASK_ID='dump_source' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T14:50:09.103548+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T14:50:09.103548+00:00'
[2024-07-12T14:50:14.149+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T14:50:14.156+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-12T14:50:14.157+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nsudo export PGPASSWORD=(-\\\\`2loJV &&\npg_dump -U etl_user_3 -h 10.82.0.4 -n source_data -f scripts/sql-scripts/ods_migration.sql source\n    ']
[2024-07-12T14:50:14.173+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T14:50:14.182+0000] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 2: syntax error near unexpected token `('
[2024-07-12T14:50:14.182+0000] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 2: `sudo export PGPASSWORD=(-\\`2loJV &&'
[2024-07-12T14:50:14.183+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-07-12T14:50:14.183+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T14:50:14.189+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-07-12T14:50:14.192+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=init_ods_layer, task_id=dump_source, run_id=manual__2024-07-12T14:50:09.103548+00:00, execution_date=20240712T145009, start_date=20240712T145014, end_date=20240712T145014
[2024-07-12T14:50:14.197+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 72 for task dump_source (Bash command failed. The command returned a non-zero exit code 2.; 7563)
[2024-07-12T14:50:14.221+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T14:50:14.231+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T14:50:14.232+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
